version: "3"
services:
  # cookit-app:
  #   container_name: cookit-app
  #   image: cookit/node-web-app
  #   restart: always
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   links:
  #     - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
